FROM amazoncorretto:17
WORKDIR /app
COPY src ./src
RUN mkdir bin
RUN javac -d bin src/utils/*.java src/Registry/*.java src/Datacenter/DataCenterInterface.java src/Client.java
CMD ["java", "-cp", "bin", "Client"]
